apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://aws.github.io/eks-charts'
    chart: aws-load-balancer-controller
    targetRevision: 1.7.1
    helm:
      parameters:
        - name: clusterName
          value: nawy-cluster
        - name: serviceAccount.create
          value: "true"
        - name: serviceAccount.name
          value: aws-load-balancer-controller
        - name: region
          value: us-east-1
        - name: vpcId
          value: "vpc-012b28d9c3f60d4f3"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
