apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: '0.9.x' 
    chart: external-secrets
    helm:
      values: |
        serviceAccount:
          create: false
          name: external-secrets-sa
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
