apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-sigs.github.io/external-dns/'
    chart: external-dns
    targetRevision: 1.14.3
    helm:
      parameters:
        - name: provider
          value: aws
        - name: policy
          value: sync 
        - name: serviceAccount.create
          value: "false" 
        - name: serviceAccount.name
          value: "external-dns" 
        - name: txtOwnerId
          value: "nawy-cluster"  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
