apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newrelic-bundle
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  project: default
  source:
    repoURL: 'https://helm-charts.newrelic.com'
    chart: nri-bundle
    targetRevision: 5.0.8
    helm:
      values: |
        global:
          customSecretName: "newrelic-key"
          customSecretLicenseKey: "licenseKey"
          cluster: "nawy-cluster"
        ksm:
          enabled: true
        kube-state-metrics:
          enabled: true
        kubeEvents:
          enabled: true

        newrelic-infrastructure:
          privileged: true
          ksm: 
            resources: 
              limits:
                memory: 256Mi
              requests:
                memory: 128Mi
                
        newrelic-logging:
          enabled: true
          
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: newrelic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true
