apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-token-sync
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager 
    kind: ClusterSecretStore
  target:
    name: github-token  
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: "git"
        url: "https://github.com/ShehabGamal689/nawy-task-platform-gitops.git"
        username: "ShehabGamal689"
        password: '{{ "{{ .github_pat }}" }}' 
  data:
    - secretKey: github_pat
      remoteRef:
        key: gitops-secrets-vault
        property: github_token
