apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: kube-system
spec:
  refreshInterval: "1h" 
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: platform-secrets 
    creationPolicy: Owner
  data:
    - secretKey: NEW_RELIC_LICENSE_KEY
      remoteRef:
        key: gitops-secrets-vault
        property: newrelic_key
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: gitops-secrets-vault
        property: github_token
