apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-secret-sync
  namespace: nawy-app       
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ghcr-login        
    template:               
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"ShehabGamal689","password":"{{ .github_token }}","auth":"{{ printf "ShehabGamal689:%s" .github_token | b64enc }}"}}}'
  data:
    - secretKey: github_token
      remoteRef:
        key: gitops-secrets-vault
        property: github_token
