- name: Bootstrap EKS with Argo CD and Monitoring
  hosts: localhost
  connection: local
  tasks:
    - name: Create System Namespaces
      ansible.builtin.shell: |
        kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
        kubectl create namespace newrelic --dry-run=client -o yaml | kubectl apply -f -
        kubectl create namespace nawy-app --dry-run=client -o yaml | kubectl apply -f -

    - name: Install Argo CD (Force Server-Side Apply)
      ansible.builtin.shell: |
        kubectl apply --server-side --force-conflicts -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    - name: Install Argo CD Image Updater
      ansible.builtin.shell: |
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.12.2/manifests/install.yaml

    - name: Apply Argo CD Root App
      ansible.builtin.shell: |
        kubectl apply --server-side --force-conflicts -f https://raw.githubusercontent.com/ShehabGamal689/nawy-task-platform-gitops/main/manifests/root-app.yaml
