helm:
  parameters:
  - name: image.repository
    value: ghcr.io/shehabgamal689/nawy-task-app
    forcestring: true
  - name: image.tag
    value: 720cc118ac1cd464b30dacf5ebab151d61e46eb5
    forcestring: true
