helm:
  parameters:
  - name: image.repository
    value: ghcr.io/shehabgamal689/nawy-task-app
    forcestring: true
  - name: image.tag
    value: d61a637c3fd6e4afa46747db3df9d3c2849208c3
    forcestring: true
