helm:
  parameters:
  - name: image.repository
    value: ghcr.io/shehabgamal689/nawy-task-app
    forcestring: true
  - name: image.tag
    value: b0f2c32af13ed0dc889d0b586482ac2f79f87e50
    forcestring: true
