replicaCount: 2

image:
  repository: ghcr.io/ShehabGamal689/nawy-task-app
  tag: "latest" 
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: "alb" 
  hosts:
    - host: nawy-app.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
